language: r
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
r_binary_packages:
   - rgdal
   - rgeos
   - sf

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
