language: r
sudo: required
cache: packages

env:
  matrix:
    - NOT_CRAN=true

before_install:
- sudo apt-get -qq update
  - sudo apt-get install -y libcurl4-openssl-dev, libgdal-dev, libproj-dev

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
