language: r
sudo: required
dist: trusty
cache: packages

env:
  matrix:
    - NOT_CRAN=true

before_install:
- sudo apt-get install -y libgdal-dev libproj-dev

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
