language: r
sudo: required
dist: trusty
r_binary_packages:
   - dplyr
   - readr
   - roxygen2
   - rlang
   - purrr
   - tibble
   - ggplot2
   - git2r
   - mapproj
   - data.table
   - Rcpp
   - stringi
   - dplyr
   - readr
   - rgdal
   - rgeos
   - raster
   - tidyr
   - purrr
   - xml2

## Set up the matrix of different runs
env:
  matrix:
  - r: release
    not_cran: true
    r_check_args: "--no-manual"
  - r: release
    not_cran: false
    r_check_args: "--no-manual --as--cran"

after_failure:
  - ./pkg-build.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
    - devtools

r_github_packages:
    - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
